### ISSUE TITLE
Footer H2 should just say footer

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#104]
<img width="134" alt="Screenshot 2024-01-26 at 11 35 39 AM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/3cf2f97f-3c67-4cf5-858a-266ee64807b8">

Remove "northwest center" just "footer"

**Comment by SteveJonesDev** [comment]
Also, can you fix the color contrast error? I know this is screen reader text but it would be good to fix it.

<img width="542" alt="Screenshot 2024-01-26 at 10 43 55 PM" src="https://github.com/equalizedigital/northwest-center/assets/2895788/3492c9b0-2f3e-4312-914e-ffece4d3f7a8">

**Comment by amberhinds** [comment]
@tronsymphony It needs to say Footer - you removed the wrong thing.

<img width="393" alt="Screenshot 2024-01-30 at 2 30 55 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/5868cacc-e69f-4355-93ef-ccf31ddc0edb">

**Comment by SteveJonesDev** [comment]
@amberhinds @tronsymphony. FYI: I've updated this in the base theme: https://github.com/equalizedigital/equalize-digital-base-theme/commit/69ad298e39e47b6548d66b732a08311fc2761f5c
