### ISSUE TITLE
Header: Sub nav text is now centered

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#135]
<img width="1787" alt="Screenshot 2024-01-29 at 2 56 20 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/a6cc0ede-5491-4ec8-9ab8-2168536f9056">

This should be left aligned.

**Comment by tronsymphony** [comment]
![Screenshot 2024-01-29 at 1 02 05 PM](https://github.com/equalizedigital/northwest-center/assets/3107547/4e2f0da2-4cf7-48fa-afbd-a5e1c1159f7a)
@amberhinds I dont see it

**Comment by amberhinds** [comment]
I don't see this anymore either. Maybe it's fixed now.
