### ISSUE TITLE
About Page: section needs to be full width

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#170]
<img width="898" alt="Screenshot 2024-01-30 at 2 14 24 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/50e4d0e4-68e3-404c-a0a7-6376675ec9a0">

The right half should be the image without any stripe of blue on the right.

This is also really hard to edit:
<img width="1329" alt="Screenshot 2024-01-30 at 2 15 48 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/cc9a0c2f-631f-403f-87f4-beff4e9ce976">

**Comment by tronsymphony** [comment]
Not sure what I can do about "This is also really hard to edit:"
