### ISSUE TITLE
Home Page Hero Block: mobile styles

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#187]
At 1000px reduce the text size 

```
.home-page-hero-block .container .title {
    font-size: 2.125rem;
    line-height: 2.9375rem;
} 
```

Then, at 760px, reduce the font size to 2rem and the line-height to 2.1rem.

On mobile set the padding top and bottom on .gb-container-a0eb5ef7 to 0.

**Comment by tronsymphony** [comment]
0 padding doenst look good

**Comment by amberhinds** [comment]
Let's see what they think about the padding.
