### ISSUE TITLE
Why are there double images in the nav menu?

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#195]
Is this correct?

<img width="1176" alt="Screenshot 2024-01-30 at 6 49 01 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/81b32a42-a84a-45cf-9d70-15aa99a6742c">

**Comment by tronsymphony** [comment]
I think its a plugin setting. Its not happening locally

**Comment by tronsymphony** [comment]
The perfmatters plugin is adding these

**Comment by amberhinds** [comment]
This is an Accessibility Checker bug. closing out.
