### ISSUE TITLE
Remove Default image fields

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#244]
These are not being used right? 

<img width="270" alt="Screenshot 2024-02-01 at 7 47 30 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/8904c29d-1fea-40e6-a8ee-346a362a6c26">

**Comment by amberhinds** [comment]
It's still there: https://northwestc1dev.wpenginepowered.com/wp-admin/themes.php?page=acf-options-site-options

**Comment by tronsymphony** [comment]
Its removed but theres no way to delete the option. ACF menu is hidden on staging

**Comment by tronsymphony** [comment]
@SteveJonesDev I cant find where this is loading from. I removed the ACF.json file from the server but its still loading.

**Comment by tronsymphony** [comment]
Had to do it through sftp
