### ISSUE TITLE
People block image fixes

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#247]
Don't change the aspect ratio these images or use full size images:
<img width="786" alt="Screenshot 2024-02-01 at 8 27 15 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/f293028e-b8f7-4c0f-a82c-8eb3cdb8ff44">
<img width="598" alt="Screenshot 2024-02-01 at 8 27 30 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/34ef6cca-9ec3-438a-92aa-4719f12a62df">

The image is 266x270 in the design.
<img width="1118" alt="Screenshot 2024-02-01 at 8 28 32 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/3a25b6fa-bce2-406a-b232-87ce2ce501e1">

Add a custom image size so that these images are always the same size.  It probably needs to be 2x the designed size.

**Comment by amberhinds** [comment]
@tronsymphony - I can see this fix even in incognito. Please confirm.

**Comment by tronsymphony** [comment]
@amberhinds The images have to be regenerated. How do you guys do that?

**Comment by tronsymphony** [comment]
![Uploading Screenshot 2024-02-03 at 4.54.43 PM.jpg…]()

**Comment by tronsymphony** [comment]
![Screenshot 2024-02-03 at 4 54 43 PM](https://github.com/equalizedigital/northwest-center/assets/3107547/db4f3dcd-e0ee-49b1-91f9-5df69ebee7d2)

**Comment by amberhinds** [comment]
Nitya, use this https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by amberhinds** [comment]
@tronsymphony this isn't just about the image size. It's the CSS.

<img width="1707" alt="Screenshot 2024-02-04 at 7 24 45 AM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/04c25492-b2ad-45cf-8e83-3ec64e13f87e">

If you remove the set height, then the custom image size is used:
<img width="1589" alt="Screenshot 2024-02-04 at 7 25 16 AM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/8f25b12a-c697-4555-b705-3200c0ee5823">

Then you need to regenerate images using the plugin linked above so this doesn't happen:
<img width="1239" alt="Screenshot 2024-02-04 at 7 26 42 AM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/05727157-d6ce-477d-a8ed-fdfa39a90e6a">

**Comment by tronsymphony** [comment]
I removed the css, but since the images are small they wont be generated into larger sizes
