### ISSUE TITLE
Overlap in editor

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#263]
https://northwestc1dev.wpenginepowered.com/wp-admin/post.php?post=3651&action=edit#

<img width="1057" alt="Screenshot 2024-02-01 at 10 59 40 PM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/d8fcb872-81b7-42ce-8092-5a07feb56baa">

**Comment by tronsymphony** [comment]
@SteveJonesDev Im not sure what the solution is here. It needs to overlap

**Comment by amberhinds** [comment]
Here's another example:
https://northwestc1dev.wpenginepowered.com/wp-admin/post.php?post=3627&action=edit
![Uploading Screenshot 2024-02-03 at 6.25.46 AM.png…]()

**Comment by tronsymphony** [comment]
@amberhinds The second one isnt a margin issue. Its a overlay svg for the separator
