### ISSUE TITLE
people single white space

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#310]
That blue section has white on either side.

<img width="679" alt="Screenshot 2024-02-04 at 6 53 56 AM" src="https://github.com/equalizedigital/northwest-center/assets/13153456/2090f923-d510-47e9-a522-3b45fc4c80c8">

**Comment by amberhinds** [comment]
It's also visible on desktop:
![Uploading Screenshot 2024-02-04 at 6.55.14 AM.png…]()

**Comment by tronsymphony** [comment]
![Screenshot 2024-02-04 at 9 36 14 AM](https://github.com/equalizedigital/northwest-center/assets/3107547/09041dc1-a57a-43b1-b508-d068a3984bcc)
Im not seeing it. are you cached?
