### ISSUE TITLE
Theme and Author URI is RWC website

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/northwest-center#326]
https://github.com/equalizedigital/northwest-center/blob/c1349568ee0d1445f0a409215327132cd6cc6ebd/style.css#L3

Make the theme uri the client's website.

Author URI should be equalizedigital.com

**Comment by SteveJonesDev** [comment]
@amberhinds, FYI, I updated this in the base theme yesterday. https://github.com/equalizedigital/equalize-digital-base-theme/commit/13f78ec93039ecaa1e8606a47e9f150e8246bae2

**Comment by amberhinds** [comment]
I saw. Thanks.
