### ISSUE TITLE
Latest Posts Block: Don't show tab if not posts are attached to that term

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/northwest-center#71]
https://github.com/equalizedigital/northwest-center/blob/2137f8eee1e0b2ad3a9724c959a7f156e15963e6/partials/blocks/latest-posts-block/template.php#L63-L76

So you don't have to do a separate query for each selected term you could use `get_terms()' with the `hide_empty` option set to `true`.

Something like this:
```php
$specific_term_ids = [1, 2, 3]; // Replace with the term IDs you want to include

$args = array(
    'taxonomy'   => 'category', // Replace with your specific taxonomy
    'include'    => $specific_term_ids,
    'hide_empty' => true, // Set to true if you want to hide empty terms
);

$terms = get_terms($args);

foreach ($terms as $term) {
    // Your code to handle each term
    echo $term->name;
    // More code as needed
}
```

**Comment by tronsymphony** [comment]
Im not really understanding the request. You need to get 3 posts per category
