### ISSUE TITLE
Latest Posts Block: Query improvements

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/northwest-center#80]
This is for both `get_posts` queries.

https://github.com/equalizedigital/northwest-center/blob/2137f8eee1e0b2ad3a9724c959a7f156e15963e6/partials/blocks/latest-posts-block/template.php#L87-L92

Since pagination isn't required set:
```php
'no_found_rows' => true, // Disables pagination count queries
```

Specify Post Status:
```php
'post_status' => 'publish',
```

Consider caching queries. Example:
```php
$cache_key = 'posts_for_term_' . $term_id;
$posts_latest = get_transient( $cache_key );

if ( false === $posts_latest ) {
    // Your WP_Query here
    set_transient( $cache_key, $posts_latest, 12 * HOUR_IN_SECONDS );
}
```

**Comment by tronsymphony** [comment]
I wasnt able to implement this
