### ISSUE TITLE
[Marker.io] Sub menus don't collapse on mobile.

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/northwest-center#85]
[![Screenshot_2024-01-26_00-18-29.png](https://mrkr.io/s/65b2fa556437fe4160704ab4/2)](https://mrkr.io/s/65b2fa556437fe4160704ab4/0)

Clicking the button doesn't collapse the subnav

---

**Reported by:** Amber (amber@equalizedigital.com) - [Contact via Marker.io](https://app.marker.io/i/65b2fa556437fe4160704ab7_cbd987112f361349?advanced=1&comments=1)

**Source URL:** [https://northwestc1dev.wpenginepowered.com/in-loving-memory-of-patrick-dolan-1950-2023/](https://northwestc1dev.wpenginepowered.com/in-loving-memory-of-patrick-dolan-1950-2023/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/65b2fa556437fe4160704ab7_cbd987112f361349?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Chrome Mobile 120.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>412 x 892</td></tr><tr><td><strong>OS</strong></td><td>Android 14.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>412 x 771</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2.625x</td></tr></table>

**Comment by tronsymphony** [comment]
I did not see this issue

**Comment by christophermhinds** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/65b2fa556437fe4160704ab7_cbd987112f361349) - This issue was marked as **✅ Resolved** in Marker.io
